.TH "dllmain.cpp" 3 "Fri Sep 7 2018" "Version 0.01" "Scrutiny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dllmain.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "BOOL APIENTRY \fBDllMain\fP (HMODULE hModule, DWORD ul_reason_for_call, LPVOID lpReserved)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOL APIENTRY DllMain (HMODULE hModule, DWORD ul_reason_for_call, LPVOID lpReserved)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Scrutiny from the source code\&.
