.TH "Scrut" 3 "Wed Sep 19 2018" "Version 0.01" "Scrutiny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Scrut \- Provide functionality for the user make simple calls to elasticsearch\&. Have the main configuration for the indexing patterns of ELK, what data types to send, etc\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHttpSocket\fP"
.br
.ti -1c
.RI "class \fBScrutiny\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provide functionality for the user make simple calls to elasticsearch\&. Have the main configuration for the indexing patterns of ELK, what data types to send, etc\&. 


.PP
\fBAuthor:\fP
.RS 4
Ben Hoffman 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Scrutiny from the source code\&.
