.TH "Scrutiny" 3 "Fri Sep 7 2018" "Version 0.01" "Scrutiny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Scrutiny \- Provide functionality for the user make simple calls to elasticsearch\&. Have the main configuration for the indexing patterns of ELK, what data types to send, etc\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Scrutiny\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScrutiny\fP ()"
.br
.ti -1c
.RI "\fB~Scrutiny\fP ()"
.br
.ti -1c
.RI "int \fBTestRequest\fP ()"
.br
.ti -1c
.RI "float \fBTestMultiply\fP (float a, float b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provide functionality for the user make simple calls to elasticsearch\&. Have the main configuration for the indexing patterns of ELK, what data types to send, etc\&. 


.PP
\fBAuthor:\fP
.RS 4
Ben Hoffman 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "Scrutiny::Scrutiny ()"
Default Consructor 
.SS "Scrutiny::~Scrutiny ()"
Default desturctor 
.SH "Member Function Documentation"
.PP 
.SS "float Scrutiny::TestMultiply (float a, float b)"

.SS "int Scrutiny::TestRequest ()"
Send a test web socket request to the ELK stack 

.SH "Author"
.PP 
Generated automatically by Doxygen for Scrutiny from the source code\&.
