.TH "ScrutinyExports.cpp" 3 "Wed Sep 26 2018" "Version 0.01" "Scrutiny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScrutinyExports.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br
\fC#include 'ScurintyExports\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBScrut::Scrutiny\fP * \fBCreateScrutiny\fP ()"
.br
.RI "Implementatoin of all exported functions\&. This has to be done with a pointer implementation because of limitations with Unity\&. "
.ti -1c
.RI "void \fBDestroyScrutiny\fP (\fBScrut::Scrutiny\fP *Impl)"
.br
.ti -1c
.RI "int \fBTestRequest\fP (\fBScrut::Scrutiny\fP *Impl)"
.br
.ti -1c
.RI "int \fBGetIndex\fP (\fBScrut::Scrutiny\fP *Impl, const char *aIndex)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBScrut::Scrutiny\fP* CreateScrutiny ()"

.PP
Implementatoin of all exported functions\&. This has to be done with a pointer implementation because of limitations with Unity\&. 
.PP
\fBAuthor:\fP
.RS 4
Ben Hoffman 
.RE
.PP

.SS "void DestroyScrutiny (\fBScrut::Scrutiny\fP * Impl)"

.SS "int GetIndex (\fBScrut::Scrutiny\fP * Impl, const char * aIndex)"

.SS "int TestRequest (\fBScrut::Scrutiny\fP * Impl)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Scrutiny from the source code\&.
