.TH "stdafx.h" 3 "Fri Sep 7 2018" "Version 0.01" "Scrutiny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stdafx.h
.SH SYNOPSIS
.br
.PP
\fC#include 'targetver\&.h'\fP
.br
\fC#include <windows\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBWIN32_LEAN_AND_MEAN\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define WIN32_LEAN_AND_MEAN"

.SH "Author"
.PP 
Generated automatically by Doxygen for Scrutiny from the source code\&.
