.TH "WebRequest.h" 3 "Fri Sep 7 2018" "Version 0.01" "Scrutiny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WebRequest.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWebRequest\fP"
.br
.RI "\fBWebRequest\fP class for interfacing with the ELK stack via sockets\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Scrutiny from the source code\&.
